link_with 'Demo','CMPLjhMobile'
platform :ios, '7.0'
inhibit_all_warnings!       #去掉所有pod生成的警告

pod 'SDWebImage', '~> 3.7.6'
pod 'FDFullscreenPopGesture'
#pod 'JSONKit'
pod 'MBProgressHUD'
#pod 'FMDB'
#pod 'Reachability', '~> 3.2'
#pod 'PinYin4Objc'
pod '    '
#pod 'UMengAnalytics-NO-IDFA', '~> 3.6.5'

pod 'AFNetworking', '~> 2.5.1'
#pod 'MJRefresh', '~> 1.4.6'
pod 'JPush-iOS-SDK', '~> 1.8.3'
pod 'pop', '~> 1.0.9'

pod 'IQKeyboardManager', '~> 4.0.3'
pod 'Masonry', '~> 1.0.0'



