source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'


target "mt_shortvideo" do
  pod 'SVProgressHUD'
#  pod 'TXIMSDK_iOS'
  pod 'TXIMSDK_TUIKit_iOS'
  pod 'AMap2DMap'
  #pod 'UMCCommon'
  #pod 'UMCCommonLog'
  #pod 'UMCAnalytics'
end
#pod update --no-repo-update
#pod install --no-repo-update


