platform :ios, '10.0'
target "mt_shortvideo" do
  pod 'SVProgressHUD'

  
  #pod 'UMCCommon'
  #pod 'UMCCommonLog'
  #pod 'UMCAnalytics'
end
#pod update --no-repo-update
#pod install --no-repo-update


